import 'package:catbreeds/models/cat_breeds.dart';

final parsedCatBreeds = [
  CatBreed(
    id: "abys",
    name: "Abyssinian",
    temperament: "Active, Energetic, Independent, Intelligent, Gentle",
    cfaUrl: "",
    vetstreetUrl: "",
    vcahospitalsUrl: "",
    origin: "Egypt",
    countryCodes: "EG",
    countryCode: "EG",
    lifeSpan: "14 - 15",
    indoor: 0,
    lap: 1,
    adaptability: 5,
    affectionLevel: 5,
    childFriendly: 3,
    dogFriendly: 4,
    energyLevel: 5,
    grooming: 1,
    healthIssues: 2,
    intelligence: 5,
    sheddingLevel: 2,
    socialNeeds: 5,
    strangerFriendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressedTail: 0,
    shortLegs: 0,
    wikipediaUrl: "",
    hypoallergenic: 0,
    referenceImageId: "0XYvRd7oD",
  )
];
